//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPRUEBA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecursosHumanosEntities1 : DbContext
    {
        public RecursosHumanosEntities1()
            : base("name=RecursosHumanosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Licencia> Licencias { get; set; }
        public virtual DbSet<Nomina> Nominas { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Salida> Salidas { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
        public virtual DbSet<CantSalida> CantSalidas { get; set; }
        public virtual DbSet<EmpleadosActivo> EmpleadosActivos { get; set; }
        public virtual DbSet<EmpleadosInactivo> EmpleadosInactivos { get; set; }
        public virtual DbSet<Entrada> Entradas { get; set; }
    
        public virtual ObjectResult<Calcular_Nomina_Result> Calcular_Nomina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Calcular_Nomina_Result>("Calcular_Nomina");
        }
    
        public virtual ObjectResult<salidasMes_Result> salidasMes(Nullable<int> mes)
        {
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<salidasMes_Result>("salidasMes", mesParameter);
        }
    }
}
